// **************
// LOCALHOST 
// **************

### READ ALL from LOCALHOST
GET http://localhost:8080/contacts 
### READ ONE from LOCALHOST
GET http://localhost:8080/contacts/6260ab666e12ccf345d9a415 


### CREATE CONTACT on LOCALHOST
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
"firstName":"Lindsey",
"lastName":"Myers",
"email":"mye19007@byui.edu",
"favoriteColor":"Black",
"birthday":"05/05/1988"
}

### UPDATE CONTACT on LOCALHOST
PUT http://localhost:8080/contacts HTTP/1.1
Content-Type: application/json
{
  "firstName":"Ron",
  "lastName":"Myers",
  "email":"rammyers@live.com",
  "favoriteColor":"Red",
  "birthday":"12/07/1954"
}

### DELETE CONTACT on LOCALHOST
DELETE http://localhost:8080/contacts/6266dda4fa235ad3d043c73f HTTP/1.1







// ********************
// PRODUCTION Deploy 
// ********************

### READ ALL from HEROKU
GET https://cse341lindseymyersl02.herokuapp.com/contacts 
### READ ONE from HEROKU
GET https://cse341lindseymyersl02.herokuapp.com/contacts/6260ab666e12ccf345d9a415 



### CREATE CONTACT on HEROKU
POST http://cse341lmyers.herokuapp.com/contacts HTTP/1.1
Content-Type: application/json
{
  "firstName":"Charlee",
  "lastName":"Myers",
  "email":"doggie@email.com",
  "favoriteColor":"Grey",
  "birthday":"01-20-2013"
}

### UPDATE CONTACT on HEROKU
PUT http://cse341lmyers.herokuapp.com/contacts HTTP/1.1
Content-Type: application/json
{
  "firstName":"Donalene",
  "lastName":"Myers",
  "email":"dmyers@live.com",
  "favoriteColor":"Blue",
  "birthday":"12/13/1956"
}

### DELETE CONTACT on HEROKU
DELETE http://cse341lmyers.herokuapp.com/contacts/6266dda4fa235ad3d043c73f HTTP/1.1
