// **************
// LOCALHOST 
// **************

### READ ALL from LOCALHOST
GET http://localhost:8080/contacts 
### READ ONE from LOCALHOST
GET http://localhost:8080/contacts/6260ab666e12ccf345d9a415 


### CREATE CONTACT on LOCALHOST
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
"firstName":"Lindsey",
"lastName":"Myers",
"email":"mye19007@byui.edu",
"favoriteColor":"Black",
"birthday":"05/05/1988"
}

### UPDATE CONTACT on LOCALHOST (Please paste in _id of correct item to update)
PUT http://localhost:8080/contacts/6260ac386e12ccf345d9a416 HTTP/1.1
Content-Type: application/json

{
  "firstName":"Zoey",
  "lastName":"Myers",
  "email":"zmyers101@outlook.com",
  "favoriteColor":"Purple",
  "birthday":"10/10/2011"
}

### DELETE CONTACT on LOCALHOST (Please paste in _id of correct item to delete)
DELETE http://localhost:8080/contacts/6260ad836e12ccf345d9a417 HTTP/1.1







// ********************
// PRODUCTION Deploy 
// ********************

### READ ALL from HEROKU
GET https://cse341lindseymyersl02.herokuapp.com/contacts 
### READ ONE from HEROKU
GET https://cse341lindseymyersl02.herokuapp.com/contacts/6260ab666e12ccf345d9a415
 



### CREATE CONTACT on HEROKU
POST http://cse341lmyers.herokuapp.com/contacts HTTP/1.1
Content-Type: application/json

{
  "firstName":"Charlee",
  "lastName":"Myers",
  "email":"doggie@email.com",
  "favoriteColor":"Grey",
  "birthday":"01-20-2013"
}

### UPDATE CONTACT on HEROKU (Please paste in _id of correct item to update)
PUT http://cse341lmyers.herokuapp.com/contacts/6260ad836e12ccf345d9a417 HTTP/1.1
Content-Type: application/json

{
  "firstName":"Zayden",
  "lastName":"Myers",
  "email":"zmyers8@outlook.com",
  "favoriteColor":"Red",
  "birthday":"08/12/2013"
}

### DELETE CONTACT on HEROKU (Please paste in _id of correct item to delete)
DELETE http://cse341lmyers.herokuapp.com/contacts/6260ac386e12ccf345d9a416 HTTP/1.1
